/**
 * Create a graph using data from a table element and Rickshaw.
 */
+function ($) {
  'use strict';

  // Assemble the object.
  var liftGraph = function (element, options) {
    this.type =
    this.options =
    this.enabled =
    this.$element = null

    this.init('liftGraph', element, options);
  };

  // Define the plugin defaults.
  liftGraph.DEFAULTS = {
    type: 'line',
    palette: 'munin'
  };

  // Initialize the plugin functionality.
  liftGraph.prototype.init = function (type, element, options) {
    this.type = type
    this.$element = $(element)
    this.options = this.getOptions(options)
    this.enabled = true

    this.render();
  };

  // Enable the graph.
  liftGraph.prototype.enable = function () {
    this.enabled = true;
  };

  // Disable the graph.
  liftGraph.prototype.disable = function () {
    this.enabled = false;
  };

  // Get the option value of a data attribute.
  liftGraph.prototype.dataAttr = function (key) {
    return this.$element.attr('data-' + this.type + '-' + key);
  };

  // Get default values.
  liftGraph.prototype.getDefaults = function () {
    return liftGraph.DEFAULTS;
  };

  // Reset the table.
  liftGraph.prototype.destroy = function () {
    this.hide().$element.off('.' + this.type).removeData('lift.' + this.type);
  }

  // Get options.
  liftGraph.prototype.getOptions = function (options) {
    options = $.extend({}, this.getDefaults(), options);
    for (var i in options) {
      options[i] = this.dataAttr(i) || options[i];
    }
    return options;
  };

  // Get the labels for the x axis.
  liftGraph.prototype.getLabelsX = function () {
    if (typeof this.labelsX == 'undefined') {
      var headers = this.$element.find('thead > tr > th'),
          labels = {};

      delete headers[0];

      headers.each(function (i) {
        if (typeof this != 'undefined') {
          labels[i - 1] = $(this).text();
        };
      });

      this.labelsX = labels;
    }

    return this.labelsX;
  }

  // Get the series data form the table.
  liftGraph.prototype.getSeries = function () {
    if (typeof this.series == 'undefined') {
      var series = [],
          palette = new Rickshaw.Color.Palette({
            scheme: 'munin'
          });

      this.$element.find('tbody > tr').each(function (row) {
        series[row] = {
          name: $(this).find('td:first-child').text(),
          color: palette.color(),
          data: []
        };

        $(this).children('td:not(td:first-child)').each(function (key) {
          series[row].data.push({x: key, y: parseFloat($(this).text())});
        });
      });

      this.series = series;
    }

    return this.series;
  }

  // Get the graph object.
  liftGraph.prototype.getGraph = function () {}

  // Render the graph.
  liftGraph.prototype.render = function () {
    var $element = this.$element.addClass('lift-graph-table'),
        labelsX = this.getLabelsX(),
        series = this.getSeries();

    var labels = function (n) {
      return labelsX[n];
    }

    this.$graph = $('<div class="lift-graph-graph"></div>');
    this.$legend = $('<div class="lift-graph-legend"></div>');

    $element.wrap('<div class="lift-graph-container"></div>').before(this.$graph).before(this.$legend);

    var graph = new Rickshaw.Graph({
          element: this.$graph[0],
          renderer: 'line',
          interpolation: 'linear',
          height: 500,
          series: this.series
        }),
        axisX = new Rickshaw.Graph.Axis.X({
          tickFormat: labels,
          graph: graph
        }),
        axisY = new Rickshaw.Graph.Axis.Y({
          graph: graph
        });

    graph.render();

    console.log(this);
  };

  // Define the jQuery plugin.
  var old = $.fn.railroad;

  $.fn.liftGraph = function (options) {
    return this.each(function () {
      var $this = $(this),
          data = $this.data('lift.graph'),
          options = typeof options == 'object' && option;

      if (!data && options == 'destroy') return;
      if (!data) $this.data('lift.graph', (data = new liftGraph(this, options)));
      if (typeof option == 'string') data[option]();
    });
  }

  $.fn.liftGraph.Constrictor = liftGraph;

  $.fn.liftGraph.noConflict = function () {
    $.fn.liftGraph = old;
    return this;
  }
}(jQuery);


/**
 * Test implementation and features.
 */
$( document ).ready(function () {
  // Use our above jQuery function on a table.
  $('table[data-liftGraph-type]').liftGraph();

  // Play with features using random data generated by Rickshaw.
  var chartWidth = function () {
    return $('#lift-chart').width();
  }

  var seriesData = [ [], [], [] ];
  var random = new Rickshaw.Fixtures.RandomData(12);

  for (var i = 0; i < 12; i++) {
  	random.addData(seriesData);
  }

  console.log(seriesData);

  var ticksTreatment = 'glow',
      xValues = function (n) {
        var map = {
          0: 'January',
          1: 'February',
          2: 'March',
          3: 'April',
          4: 'May',
          5: 'June',
          6: 'July',
          7: 'August',
          8: 'September',
          9: 'October',
          10: 'November',
          11: 'December'
        }

        return map[n]
      },
      palette = new Rickshaw.Color.Palette({
        scheme: 'munin'
      }),
      graph = new Rickshaw.Graph({
        element: document.querySelector('#lift-chart'),
        renderer: 'line',
        interpolation: 'linear',
        height: 500,
        series: [
          {
            name: 'Stuff',
            color: palette.color(),
            data: seriesData[0]
          },
          {
            name: 'More stuff',
            color: palette.color(),
            data: seriesData[1]
          },
          {
            name: 'Look at all of this stuff!',
            color: palette.color(),
            data: seriesData[2]
          }
        ]
      }),
      hover = new Rickshaw.Graph.HoverDetail({
        graph: graph
      }),
      highlight = new Rickshaw.Graph.Behavior.Series.Highlight({
        graph: graph
      }),
      toggle = new Rickshaw.Graph.Behavior.Series.Toggle({
        graph: graph
      }),
      axisX = new Rickshaw.Graph.Axis.X({
        // tickFormat: xValues,
        // pixelsPerTick: 20,
        orientation: 'top',
        ticksTreatment: ticksTreatment,
        graph: graph
      }),
      axisY = new Rickshaw.Graph.Axis.Y({
        timeFixture: new Rickshaw.Fixtures.Time('month'),
        ticksTreatment: ticksTreatment,
        graph: graph
      }),
      legend = new Rickshaw.Graph.Legend({
        element: document.querySelector('#lift-chart-legend'),
        graph: graph
      }),
      toggly = new Rickshaw.Graph.Behavior.Series.Toggle({
      	graph: graph,
      	legend: legend
      }),
      order = new Rickshaw.Graph.Behavior.Series.Order( {
      	graph: graph,
      	legend: legend
      } ),
      highlighter = new Rickshaw.Graph.Behavior.Series.Highlight( {
      	graph: graph,
      	legend: legend
      } ),
      smoother = new Rickshaw.Graph.Smoother( {
      	graph: graph,
      	element: document.querySelector('#smoother')
      } );

  graph.render();
});
